version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:

  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: resistordocker/foodgram_backend
    env_file: ../.env
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    image: resistordocker/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/  # сюда скопирован ollected_static
      - media_value:/var/html/media/  # это откуда возьмётся?
    depends_on:
      - frontend
      - backend