version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:

  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - /var/lib/postgresql/data

  backend:
    build:
      dockerfile: ../backend/Dockerfile
      context: ../backend
    restart: always
    env_file:
      - ../.env
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/  # здесь отличие с продакшеном

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
#      - ../static:/var/html/backend_static/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
      - frontend
