version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:

  db:
    image: postgres:13
    env_file: ../.env
    volumes:
#      - /var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: resistordocker/foodgram_backend
    restart: always
    env_file:
      - ../.env
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    image: resistordocker/foodgram_frontend
    volumes:
#      - ../frontend/:/app/result_build/
     - static_value:/app/result_build/

# можно через это, но тогда надо ещё в папку на сервере копировать nginx.conf через workflow
#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "8080:80"
#    volumes:
#      - static_value:/var/html/backend_static/
#      - media_value:/var/html/media/
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs/:/usr/share/nginx/html/api/docs/
#    restart: always
#    depends_on:
#      - backend
#      - frontend

  gateway:
    image: resistordocker/kittygram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static_value:/var/html/backend_static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
        - backend
        - frontend
