# Generated by Django 3.2.20 on 2023-08-19 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ingredient', max_length=60, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(help_text='How much of the ingredient is needed')),
                ('unit_of_measurement', models.CharField(help_text='Units of measurement for the ingredient', max_length=16)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag', max_length=30, unique=True)),
                ('colour_code', models.CharField(max_length=7)),
                ('slug', models.SlugField(help_text='Slug for the tag', max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the recipe', max_length=200)),
                ('description', models.TextField(help_text='Description of the recipe', max_length=600)),
                ('image', models.ImageField(upload_to='recipes/')),
                ('time_to_cook', models.PositiveSmallIntegerField(help_text='Time to cook according to the recipe')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipes.Ingredient')),
                ('tags', models.ManyToManyField(related_name='recipes', to='recipes.Tag')),
            ],
            options={
                'verbose_name': ('Recipe',),
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
