# Generated by Django 3.2.20 on 2023-08-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='colour_code',
            new_name='color',
        ),
    ]
