# Generated by Django 3.2.20 on 2023-09-19 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Time to cook according to the recipe', validators=[django.core.validators.MinValueValidator(limit_value=1, message="Cooking time can't be less than 1 minute")]),
        ),
    ]
