# Generated by Django 3.2.20 on 2023-09-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230823_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscription',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_follow',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscription'),
        ),
    ]
